create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create type public.app_role as enum ('customer', 'admin');
create type public.product_status as enum ('available', 'sold_out', 'archived', 'coming_soon');
create type public.event_status as enum ('upcoming', 'ongoing', 'past', 'cancelled');
create type public.order_status as enum ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded');
create type public.payment_status as enum ('unpaid', 'paid', 'refunded');
create type public.inventory_movement_type as enum ('sale', 'restock', 'adjustment', 'cancellation');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_email_format check (email is null or email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create table public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table public.categories (
  id bigint primary key generated by default as identity,
  name text not null,
  slug text not null unique,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_not_blank check (btrim(name) <> ''),
  constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table public.products (
  id bigint primary key generated by default as identity,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  slug text not null unique,
  description text,
  status public.product_status not null default 'available',
  is_featured boolean not null default false,
  has_sizes boolean not null default true,
  weight_grams integer,
  meta_title text,
  meta_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_name_not_blank check (btrim(name) <> ''),
  constraint products_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint products_weight_nonnegative check (weight_grams is null or weight_grams >= 0)
);

create index products_category_id_idx on public.products(category_id);
create index products_status_idx on public.products(status);
create index products_featured_idx on public.products(is_featured) where is_featured;

create table public.product_variants (
  id bigint primary key generated by default as identity,
  product_id bigint not null references public.products(id) on delete cascade,
  sku text not null unique,
  size text not null default 'OS',
  color text not null default '',
  price numeric(12, 2) not null,
  compare_at_price numeric(12, 2),
  stock_quantity integer not null default 0,
  low_stock_threshold integer not null default 5,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, size, color),
  constraint variants_sku_not_blank check (btrim(sku) <> ''),
  constraint variants_size_not_blank check (btrim(size) <> ''),
  constraint variants_price_nonnegative check (price >= 0),
  constraint variants_compare_price_valid check (compare_at_price is null or compare_at_price >= price),
  constraint variants_stock_nonnegative check (stock_quantity >= 0),
  constraint variants_threshold_nonnegative check (low_stock_threshold >= 0)
);

create index product_variants_product_id_idx on public.product_variants(product_id);
create index product_variants_active_idx on public.product_variants(product_id, is_active);

create table public.product_images (
  id bigint primary key generated by default as identity,
  product_id bigint not null references public.products(id) on delete cascade,
  object_path text not null unique,
  alt_text text,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  constraint product_images_safe_path check (
    object_path !~ '(^|/)\.\.(/|$)'
    and object_path ~ '^products/[A-Za-z0-9/_-]+\.(jpg|jpeg|png|webp)$'
  )
);

create index product_images_product_id_idx on public.product_images(product_id, sort_order);
create unique index product_images_one_primary_idx on public.product_images(product_id) where is_primary;

create table public.customers (
  id bigint primary key generated by default as identity,
  user_id uuid unique references auth.users(id) on delete set null,
  first_name text not null,
  last_name text not null default '',
  email text not null,
  phone text,
  email_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customers_name_not_blank check (btrim(first_name) <> ''),
  constraint customers_email_lowercase check (email = lower(email)),
  constraint customers_email_format check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create unique index customers_email_unique_idx on public.customers(lower(email));

create table public.customer_addresses (
  id bigint primary key generated by default as identity,
  customer_id bigint not null references public.customers(id) on delete cascade,
  label text not null default 'Home',
  address_line1 text not null,
  address_line2 text,
  city text not null,
  province text,
  postal_code text,
  country text not null default 'Philippines',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index customer_addresses_customer_id_idx on public.customer_addresses(customer_id);
create unique index customer_addresses_one_default_idx on public.customer_addresses(customer_id) where is_default;

create table public.orders (
  id bigint primary key generated by default as identity,
  order_number text not null unique,
  idempotency_key uuid not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  customer_user_id uuid references auth.users(id) on delete set null,
  guest_email text,
  status public.order_status not null default 'pending',
  payment_method text not null default 'cod',
  payment_status public.payment_status not null default 'unpaid',
  payment_reference text,
  shipping_name text not null,
  shipping_email text not null,
  shipping_phone text not null,
  shipping_address text not null,
  shipping_city text not null,
  shipping_province text,
  shipping_postal text,
  shipping_country text not null default 'Philippines',
  subtotal numeric(12, 2) not null,
  shipping_fee numeric(12, 2) not null default 0,
  discount_amount numeric(12, 2) not null default 0,
  total numeric(12, 2) not null,
  notes text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_number_format check (order_number ~ '^7SS-[A-F0-9]{8}$'),
  constraint orders_email_format check (shipping_email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
  constraint orders_payment_method check (payment_method in ('cod', 'gcash', 'bank')),
  constraint orders_amounts_nonnegative check (
    subtotal >= 0 and shipping_fee >= 0 and discount_amount >= 0 and total >= 0
  ),
  constraint orders_total_consistent check (total = subtotal + shipping_fee - discount_amount)
);

create index orders_customer_user_id_idx on public.orders(customer_user_id);
create index orders_status_idx on public.orders(status);
create index orders_created_at_idx on public.orders(created_at desc);

create table public.order_items (
  id bigint primary key generated by default as identity,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  variant_id bigint references public.product_variants(id) on delete set null,
  product_name_snapshot text not null,
  sku_snapshot text not null,
  size_snapshot text not null,
  color_snapshot text not null default '',
  unit_price_snapshot numeric(12, 2) not null,
  quantity integer not null,
  line_total numeric(12, 2) not null,
  created_at timestamptz not null default now(),
  constraint order_items_price_nonnegative check (unit_price_snapshot >= 0),
  constraint order_items_quantity_positive check (quantity > 0),
  constraint order_items_total_consistent check (line_total = unit_price_snapshot * quantity)
);

create index order_items_order_id_idx on public.order_items(order_id);
create index order_items_product_id_idx on public.order_items(product_id);

create table public.inventory_movements (
  id bigint primary key generated by default as identity,
  variant_id bigint not null references public.product_variants(id) on delete restrict,
  order_id bigint references public.orders(id) on delete set null,
  movement_type public.inventory_movement_type not null,
  quantity_delta integer not null,
  stock_after integer not null,
  reason text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint inventory_movements_nonzero check (quantity_delta <> 0),
  constraint inventory_movements_stock_nonnegative check (stock_after >= 0)
);

create index inventory_movements_variant_id_idx on public.inventory_movements(variant_id, created_at desc);
create index inventory_movements_order_id_idx on public.inventory_movements(order_id);

create table public.events (
  id bigint primary key generated by default as identity,
  title text not null,
  slug text not null unique,
  description text,
  event_date timestamptz not null,
  end_date timestamptz,
  location_name text,
  location_address text,
  location_lat numeric(10, 7),
  location_lng numeric(10, 7),
  poster_object_path text,
  max_rsvp integer not null default 0,
  rsvp_count integer not null default 0,
  status public.event_status not null default 'upcoming',
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint events_title_not_blank check (btrim(title) <> ''),
  constraint events_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint events_end_after_start check (end_date is null or end_date >= event_date),
  constraint events_capacity_nonnegative check (max_rsvp >= 0 and rsvp_count >= 0),
  constraint events_capacity_valid check (max_rsvp = 0 or rsvp_count <= max_rsvp),
  constraint events_coordinates_valid check (
    (location_lat is null and location_lng is null)
    or (location_lat between -90 and 90 and location_lng between -180 and 180)
  )
);

create index events_date_idx on public.events(event_date);
create index events_status_idx on public.events(status);

create table public.event_rsvps (
  id bigint primary key generated by default as identity,
  event_id bigint not null references public.events(id) on delete cascade,
  name text not null,
  email text not null,
  phone text,
  created_at timestamptz not null default now(),
  unique (event_id, email),
  constraint event_rsvps_name_not_blank check (btrim(name) <> ''),
  constraint event_rsvps_email_lowercase check (email = lower(email)),
  constraint event_rsvps_email_format check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create index event_rsvps_event_id_idx on public.event_rsvps(event_id);

create table public.event_gallery (
  id bigint primary key generated by default as identity,
  event_id bigint not null references public.events(id) on delete cascade,
  object_path text not null unique,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint event_gallery_safe_path check (
    object_path !~ '(^|/)\.\.(/|$)'
    and object_path ~ '^events/[A-Za-z0-9/_-]+\.(jpg|jpeg|png|webp)$'
  )
);

create index event_gallery_event_id_idx on public.event_gallery(event_id, sort_order);

create table public.newsletter_subscribers (
  id bigint primary key generated by default as identity,
  email text not null,
  name text,
  is_active boolean not null default true,
  subscribed_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  constraint newsletter_email_lowercase check (email = lower(email)),
  constraint newsletter_email_format check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create unique index newsletter_email_unique_idx on public.newsletter_subscribers(lower(email));

create table public.wishlists (
  customer_id bigint not null references public.customers(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (customer_id, product_id)
);

create table public.audit_logs (
  id bigint primary key generated by default as identity,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  ip_address inet,
  created_at timestamptz not null default now(),
  constraint audit_action_not_blank check (btrim(action) <> '')
);

create index audit_logs_actor_idx on public.audit_logs(actor_user_id, created_at desc);
create index audit_logs_entity_idx on public.audit_logs(entity_type, entity_id, created_at desc);

create table private.newsletter_rate_limits (
  request_hash text primary key,
  window_started_at timestamptz not null default now(),
  attempts integer not null default 1,
  constraint newsletter_rate_attempts_positive check (attempts > 0)
);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profiles', 'categories', 'products', 'product_variants', 'customers',
    'customer_addresses', 'orders', 'events'
  ] loop
    execute format(
      'create trigger set_%1$s_updated_at before update on public.%1$I for each row execute function private.set_updated_at()',
      table_name
    );
  end loop;
end;
$$;

revoke all on all tables in schema public from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon, authenticated;
revoke all on all functions in schema public from public, anon, authenticated;
revoke all on all functions in schema private from public, anon, authenticated;
